### PR TITLE
Added a "-H" parameter to show a full YYYY-MM-DD hh:mm:ss.uuu timestamp

### PR DESCRIPTION
**Pull request by dsdee**
in the log.  Added parameters to allow this (LOGFIELDS) to the
/etc/sysconfig/passivends and to process it from the
/etc/init.d/passivedns (redhat) file.  This parametr is *not* set as a
default to the '-f' parameter -- I left that as 'S'.

### CODE REVIEW

**Comment by shadowbq** [comment]
:+1:

**Comment by dsdee** [comment]
(it's done; it just needs gamelinux to do the merge)

**Comment by gamelinux** [comment]
Thanks!

**Comment by dsdee** [comment]
Awesome.  Thanks!

**Pull request merged**
